#spring:
#  datasource:
#    url:
#    username:
#    password:
#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#      dialect : org.hibernate.dialect.PostgreSQL94Dialect

#application:
#  security:
#    jwt:
#      secret-key:
#      expiration: 86400000 # a day
#      refresh-token:
#        expiration: 604800000 # 7 days